services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password       
      - POSTGRES_USER=postgres                     
      - POSTGRES_DB=simple_blog_api                                             
  api:
    build: ./
    image: docker.io/kabhilasha/simple_blog_api                     
    environment:
      - POSTGRES_HOST=postgress                   
      - POSTGRES_PORT=5432                        
      - POSTGRES_USER=postgres               
      - POSTGRES_PASSWORD=postgres_password       
      - POSTGRES_DB=simple_blog_api              
      - PORT=3000                                                                 
    ports:
      - "3000:3000"                               

