# Set the base image
FROM docker.io/node:18-alpine
# Create the working directory
WORKDIR /usr/app
#Copy the package json first
COPY ./package.json ./
# Run the command to install dependencies
RUN npm install
#Copy the rest of the files in to the container 
# Copy src(host/path) dest(container/path)
COPY ./ ./
#The command to run on container startup
#This will start the Nodejs app
CMD ["npm", "start"]